CREATE PROC ConsPatient
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, CPF, EMAIL, WHATSAPP FROM PATIENTS WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, EMAIL, WHATSAPP FROM PATIENTS WITH(NOLOCK) WHERE ID = @ID
END