CREATE PROC PatientV2
    @NOME           VARCHAR (50) ,
    @CPF            VARCHAR(11),
    @EMAIL          VARCHAR (2079),
    @WHATSAPP       VARCHAR(12)
AS
BEGIN
	INSERT INTO PATIENTS (NOME, CPF, EMAIL, WHATSAPP) 
	VALUES (NOME, CPF, EMAIL, WHATSAPP)

	SELECT SCOPE_IDENTITY()
END